"""empty message

Revision ID: a14582cc8951
Revises: 63f487313801
Create Date: 2020-09-25 15:02:01.584805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14582cc8951'
down_revision = '63f487313801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_template')
    op.drop_column('user', 'avatar')
    op.drop_column('skill', 'level')
    op.drop_column('languages', 'level')
    # ### end Alembic commands ###
